apiVersion: v1
kind: Service
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: coder
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: code-server
  type: LoadBalancer
