apiVersion: v1
kind: PersistentVolume
metadata:
  name: coder-pv
  labels:
    volume: coder-pv
spec:
  storageClassName: manualnfs
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/coder-project
    server: 192.168.0.10
